import Head from "next/head";
import { useEffect, useState } from "react";
import { ItemType } from "@/Types/types";
import { getProducts } from "@/Network/API";
import ItemList from "@/Components/ItemList";
import Navbar from "@/Components/Navbar";
import Loader from "@/Components/Loader";

export default function Home() {
  const [itemData, setItemData] = useState();
  const getData = async () => {
    const items = await getProducts();
    setItemData(items);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      {itemData ? <ItemList items={itemData} /> : <Loader />}
    </>
  );
}
